name: 'Setup Erg environment'
description: 'Setup a Erg environment by adding problem matchers and optionally downloading and adding it to the PATH'
author: 'Erg lang team'
inputs:
  erg-version:
    required: false
    default: '0.5.9'
    description: 'Version Spec of the version to use.  Examples: 0.5.9'
runs:
  using: node16
  main: main.js
