name: Test

permissions:
  contents: write

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: erg-lang/setup-erg@v1.5
    - name: Run script
      run: |
        erg --version
        echo 'print! "hello, world!"' | erg
